version: '2'

volumes:
  data_dir:
  db:

services:
  db:
    image: "postgres:11-alpine"
    restart: always
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    image: "nextcloud:fpm-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
    depends_on:
      - db
    volumes:
      - data_dir:/var/www/html
    restart: always
    networks:
      - caddy
      - default

#    news_updater:
#      build: news_updater
#      environment:
#        NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
#        NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
#      depends_on:
#        - app
#      restart: always
#      networks:
#        - caddy

networks:
    caddy:
        external:
            name: caddy_default
