version: '2'

volumes:
  data_dir:
  db:

services:
  db:
    image: "postgres:alpine"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    expose: 
      - "5432"

  app:
    image: nextcloud:fpm
    links:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
    depends_on:
      - db
    volumes:
      - data_dir:/var/www/html
    restart: always
    networks:
      - caddy
      - default

  news_updater:
    build: news_updater
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
    depends_on:
      - app
    restart: always
    networks:
      - caddy

networks:
    caddy:
        external:
            name: caddy_default
