version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: "postgres:alpine"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    expose: 
      - "5432"

  app:
    image: nextcloud:fpm
    links:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
